"""fix events table columns

Revision ID: 21f5c1da95c7
Revises: 6db1cb7b1e76
Create Date: 2026-04-19 01:29:50.448712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21f5c1da95c7'
down_revision: Union[str, None] = '6db1cb7b1e76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('start_datetime', sa.DateTime(), nullable=False))
    op.add_column('events', sa.Column('end_datetime', sa.DateTime(), nullable=False))
    op.drop_column('events', 'start_date')
    op.drop_column('events', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('end_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('events', sa.Column('start_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('events', 'end_datetime')
    op.drop_column('events', 'start_datetime')
    # ### end Alembic commands ###

